config/routes.rb
Twitter::Application.routes.draw do

  get "homepage/home"
  get "users/show"
  delete "posts/destroy"
  get "users/show"
  post "homepage/create"

  devise_for :users
  
  resources :users , :only => [:show , :index, :follow, :unfollow]
  resources :posts , :only => :destroy
  resources :relationships , :only => [:create, :destroy]

  root :to => 'homepage#home'












end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
        can :destroy, Post, :user_id => user.id
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  attr_accessible :content, :user_id

  validates :user_id , :presence => true
  validates :content, :allow_blank => false, :presence=> true

  def self.from_users_followed_by(user)
    followed_user_ids = user.followed_user_ids
    where("user_id IN (?) OR user_id = ?", followed_user_ids, user)
  end

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id, :follower_id

  validates_uniqueness_of :follower_id, :scope => [:followed_id]

  belongs_to :follower, :class_name => User
  belongs_to :followed, :class_name => User
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts , :dependent => :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :relationships, :foreign_key => :follower_id , :dependent => :destroy
  has_many :followeds, :through => :relationships

  has_many :reverse_relationships, :class_name => Relationship, :foreign_key => :followed_id, :dependent => :destroy
  has_many :followers, :through => :reverse_relationships

  def following?(other_user)
    self.relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    self.relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    self.relationships.find_by_followed_id(other_user.id).destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def home
    @posts = Post.all
    # @followed_users = current_user.followed_users
    # @followers = current_user.followers
    # @feed = current_user.feed
  end

  def create
    my_post =  params['post_form_for']['my_new_post']
    @new_post=current_user.posts.create(:content=>my_post)
    redirect_to(homepage_home_path,notice:"new post has been created successfully")
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  load_and_authorize_resource :only => [:destroy]

  def destroy
    post = Post.find(params[:id])
    post.destroy
  	redirect_to root_path
  end

  def create
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    redirect_to @user
  end
  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    redirect_to @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @all_users = User.all
  end

  # def show
  #   @user = params[:id]
  # 	@posts = current_user.posts
  # end
  def show
    @user_posts = User.find(params[:id]).posts
    @following = User.find(params[:id]).followeds
    @followers = User.find(params[:id]).followers
    @user = User.find(params[:id])
  end

  def following
    @following_users = User.find(params[:id]).followed_users
  end

  def followers
    @followers = User.find(params[:id]).followers
  end

  def follow(user_id)
    Relationship.create(:follower_id => user_id, :followed_id => current_user.id ).save
  end

  def unfollow(user_id)
    Relationship.destroy(
        Relationship.find_by_sql("select * from relationships
        where follower_id = #{current_user.id} and followed_id = #{user_id}") )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homepage/home.html.erb
<h1><%= current_user.email %></h1>

<h3>Create new post </h3>
<%= form_tag :action => "create" do %>
    <%= text_area :post_form_for, :my_new_post, :cols => '40', :rows => '5' %>
    <%= submit_tag "Post" %>
<% end %>



<h3>Timeline</h3>
<table>

  <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <% if current_user.posts.include? post %>
            <td>&nbsp;<%= link_to("Delete", posts_destroy_path(:id => post.id), :method => :delete) %> </td>
        <% end %>
      </tr>
  <% end %>


</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Twitter</title>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
	<%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Mini Twitter" , root_url , :class=>"navbar-brand" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
		    						<li>
                        <%= link_to "Users" , users_path %>
                    </li>
                    <%if user_signed_in? %>
                    <li>
                        <%= link_to "Profile" , user_path(current_user.id)%>
                    </li>
                    <li>
                        <%= link_to "sign out" , destroy_user_session_path , :method => "delete" %>
                    </li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        <% if notice%>
       <p class="alert alert-info"><%= notice %></p>
	<% end %>
	<% if alert %>
       <p class="alert alert-danger"><%= alert %></p>
	<% end %>
	<%= yield %>
    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id)) do |f| %>
<div><%= f.hidden_field :followed_id %></div>
<%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user),
html: { method: :delete }) do |f| %>
<%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/display.html.erb
<h1> Registered Users </h1>
<ul>
	<% @all_users.each do |user| %>
      <li>
      	<%= link_to user.email, user_path(:id => user.id), :method => :get %>
      </li>
   <% end %>
</ul>


  

app/views/users/followers.html.erb
<h1>Users#followers</h1>
<p>Find me in app/views/users/index.html.erb</p>
<% if flash[:notice] %>
<div id="notice"><%= flash[:notice] %></div>
<% end %>

<table>
<% @followers.each do |user| %>
 <tr> <td><%= user.id %></td>
      <td>&nbsp;<%=link_to user.email,user_path(:id=>user.id) %> </td> 
 </tr>
<% end %>
</table>

app/views/users/following.html.erb
<h1>Users#following</h1>
<p>Find me in app/views/users/index.html.erb</p>
<% if flash[:notice] %>
<div id="notice"><%= flash[:notice] %></div>
<% end %>

<table>
<% @following_users.each do |user| %>
 <tr> <td><%= user.id %></td>
      <td>&nbsp;<%=link_to user.email,user_path(:id=>user.id) %> </td> 
 </tr>
<% end %>
</table>

app/views/users/index.html.erb
<h1> Registered Users </h1>
<ul>
  <% @all_users.each do |user| %>
      <li>
        <%= link_to user.email, user_path(:id => user.id), :method => :get %>
      </li>
  <% end %>
</ul>




app/views/users/show.html.erb
<% if @user.id.to_i == current_user.id %>
    The posts for user:
    <b>
      <%= current_user.email %>
    </b>
    <br/>
    <br/>
    <table border="1">
      <tr style="width: 60%">
        <td style="width: 80%">
          Tweet
        </td>
        <td style="width: 20%">
          Delete?
        </td>
      </tr>

      <% @user_posts.each do |post| %>
          <tr>
            <td>
              <%= post.content %>
            </td>
            <td>
              <%= link_to "delete", post_path(:id=>post.id), :method => "DELETE" %>
            </td>
          </tr>
      <% end %>
    </table>

<% else %>
    User id is : <%= @user %>
    <br/>
    <%= link_to "follow", relationships_path, :method => "put" %>
    <%= link_to "unfollow", relationship_path(@user), :method => "put" %>
<% end %>

  